# -*- coding: utf-8 -*-
"""TALLER 01 - Tipos de Datos Básicos en Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggXQE6x8Q5C9aYMUjhJ2IDE_ETC6uzMc

#**Taller 01 - Proyecto de uso de tipos de datos básicos en Python**

####**Docente:** Ing. Ivan Acosta, Mgs.
####**Nivel:** Ingeniería
####**Materia:** Programación Avanzada
####**Lenguaje**: Python

## **Descripción del Problema**

El presente taller tiene como objetivo explorar y comprender los tipos de datos básicos y avanzados en Python, así como las estructuras de control fundamentales. Se busca que los participantes adquieran las habilidades necesarias para manipular y organizar información de manera eficiente en el lenguaje de programación Python, sentando las bases para desarrollos más complejos.

## **Objetivo General**

Capacitar a los estudiantes en el uso y aplicación de los tipos de datos básicos y avanzados de Python, así como en la creación de funciones y procedimientos, para resolver problemas de programación de manera estructurada y eficiente.

## **Objetivos Específicos**

1. Identificar y diferenciar los tipos de datos primitivos (enteros, flotantes, cadenas, booleanos) y estructuras de datos básicas (listas, tuplas, diccionarios) en Python, comprendiendo sus características y casos de uso.
2. Implementar funciones y procedimientos en Python para modularizar el código y mejorar la reutilización, aplicando la sintaxis y los principios de la programación estructurada.
3. Desarrollar la capacidad de manipular y acceder a datos dentro de estructuras complejas como listas de listas y diccionarios con listas, para la gestión eficiente de conjuntos de información.

## **Objetivo de Aprendizaje**

Al finalizar esta práctica, el estudiante será capaz de identificar, manipular y organizar eficientemente información utilizando los tipos de datos básicos y avanzados de Python, aplicando funciones y procedimientos para resolver problemas de programación.

#**1 - TIPOS DE DATOS BASICOS**

**Python tiene varios tipos de datos básicos** que son fundamentales para la programación. Aquí te dejo una breve descripción de cada uno y un ejemplo práctico que puedes ejecutar en Google Colab.

**Tipos de Datos Básicos en Python**
*   Enteros (int): Números enteros, positivos o negativos, sin decimales.
*   Flotantes (float): Números con decimales.
*   Cadenas de texto (str): Secuencias de caracteres.
*   Booleanos (bool): Valores de verdad, True o False.
*   Listas (list): Colecciones ordenadas y mutables de elementos.
*   Tuplas (tuple): Colecciones ordenadas e inmutables de elementos.
*   Diccionarios (dict): Colecciones de pares clave-valor.

##1.1 - **Comentarios en el código Python**

"
 Esto es
 un comentario
 de varias
 líneas.

##**1.2 - Enteros (int)**
"""

# Entero -  (int): Números enteros, positivos o negativos, sin decimales.

numero_entero_pos = 10
numero_entero_neg = -20

print(numero_entero_pos)
print(numero_entero_neg)

# Entero -  (int): Números enteros, positivos o negativos, sin decimales.
numero_entero_pos = 10
numero_entero_neg = -20

print("Primer Numero Positivo" , numero_entero_pos)
print("Primer Numero Negativo" , numero_entero_neg)

# Entero -  (int): Números enteros, positivos o negativos, sin decimales.
# uso del operador f-String
numero_entero_pos = 10
numero_entero_neg = -20

print(f"Primer Numero Positivo {numero_entero_pos} ")
print(f"Primer Numero Negativo {numero_entero_neg} ")

# Entero -  (int): Números enteros, positivos o negativos, sin decimales.
# uso del operador f-String
edad = 50
estatura = 170
mesada = 300
temperatura = 37

print(f"Su edad es {edad}, usted mide {estatura} cm de altura, y ocupa ${mesada} al mes, posee una temperatura de {temperatura} grados centigrados")

#Posible estándar de nombres de Empresa1
gravedad_tierra_entero = 10

#Posible estándar de nombres de Empresa2
gravedadTierraEntero = 10

"""##**1.3 - Flotantes (float)**"""

# Flotante - (float): Números con decimales.

temperatura_flotante = 37.8

print(f"Su temperatura actual de {temperatura_flotante}, es aceptable")

gravedad_tierra_flotante = 9.8

# Flotante - (float): Números con decimales.

temperatura_flotante = 40.3

print(f"Su temperatura actual de {temperatura_flotante}, no es aceptable, esta en pelido de un infarto")

"""##**1.4 - Cadenas de caracteres (str)**"""

# Cadena de texto - (str): Secuencias de caracteres.

"""
  Lenguajes Previos: C, C++, C#, java, php, etc
"""
# En varios leguajes previos el estándar es este para crear cadenas:
# variable_texto      = " Hola, soy alumno del curso de Python "
# En varios leguajes previos el estándar para variables de un carater:
# variable_un_simbolo = 'H'

#****************************

#En Python Forma1 de crear una cadena de texto
cadena1_texto = "Hola, soy alumno del curso de Python"
print(f"Mensaje contenido en la Cadena dice: {cadena1_texto}")

cadena1_texto = "Hoy es sábado y el cuerpo lo sabe"
print(f"Ahora la primera cadena posee el mensaje: {cadena1_texto}")

#En Python Forma2 de crear una cadena de texto
cadena2_texto = 'Hola, soy una cadena nueva en Python'
print(f"Segunda cadena creada con comillas simples: {cadena2_texto}")

"""##**1.5 - Booleanos**"""

# Booleano - (bool): Valores True (Verdad), False (Falso).

primer_valor_booleano = True #(1)

print(f"El primer Booleano contiene un valos de: {primer_valor_booleano}")

segundo_valor_booleano = False  #(0)
print(f"El segundo Booleano contiene un valos de: {segundo_valor_booleano}")

"""##**1.6 - Listas**"""

# Lista -  (list): Colecciones ordenadas y mutables de elementos (modificables).

# nom_lista = [  elemento1, elemento2, ...,   ,elementon   ]

primera_lista = [1, 2, 6, 4, 5]

print(f"  Lista1:  {primera_lista}   ")
print("  Lista1:   {primera_lista}   ")

segunda_lista = [1, 2, "Ivan", 4, 'python', 9.8 ]
print(f"  Lista2a:  {segunda_lista}   ")

#El lenguage Python es Case Sensitive, en los nombres de las variables
# las mayusculas y las minusculas son diferentes

Segunda_lista = [4, 8, "Luis", 17, 'PHP', 9.82 ]
print(f"  Lista2b:  {Segunda_lista}   ")

print(f"  Lista2a:  {segunda_lista}   ")

segunda_Lista = [19, 32, "Pedro", 40, 'C#', 987 ]
print(f"  Lista2c:  {segunda_Lista}   ")

# Una lista si es mutable
# se puede cambiar o modificar sus elementos ya construidos

# posiciones van desde el indice 0
#                  0   1   2   3   4   5
tercera_lista = [ 21, 22, 25, 40, 50, 100 ]
print(f"  Lista3:  {tercera_lista}   ")

# Para cambiar un elemento
# se especifica el indice de unbicacón del elemento a cambiar
tercera_lista[3] = 63
print(f"  Lista3:  {tercera_lista}   ")

"""##**1.7 - Tupla**"""

# Tupla - (tuple): Colecciones ordenadas e inmutables de elementos (no se puede modificar).

# nom_tupla = (elemento1, elemento2, ...,   ,elementon )

tupla1_datos = (1, 2, 3, 4, 5)
print("Datos iniciales el la tupla 1:" , tupla1_datos )

# Podemos cambiar toda la tupla remplazando un aelemento o varios
# No podemos cambiar un unico elemanto de una tupla ya existente

# Los datos se ubiucaran en otro espacio de memoria ram pero con el nombre similar de la tupla

tupla1_datos = (4, 6, 8, 40, 15)
print("Datos finales el la tupla 1:" , tupla1_datos )

"""##**1.8 - Diccionario**"""

# Diccionario - (dict): Colecciones de pares clave-valor.

# nom_diccionario = {"clave1": "valor1", "clave2": "valor2"}
# nom_diccionario = {"tema1": "descripcion1", "tema2": "descroopcion2"}

primer_diccionario = {"Sayrami": "Estudiante de niveles avanzados de la carrera Telemátrica", "Ovalle": "Ingeniero docente de la Facultad de II", "IAcosta": "Instructor del cuero de Python"}

print(f"Diccionario: {primer_diccionario}")

"""##**1.9 - Nota - Tipos de datos inmutables**

En programación, algo inmutable es un objeto cuyo estado no puede ser modificado después de su creación. En Python, algunos ejemplos de tipos de datos inmutables son:

*   Cadenas de texto (str)
*   Tuplas (tuple)
*   Números (int, float, complex)
*   Booleanos (bool)
"""

# Ejemplo con una cadena de texto

cadena = "Este es un saludo Hola"

# Intentar modificar un carácter de la cadena dará un error
# cadena[0] = "O"  # Esto causará un error

# las cadenas ya creadas no se puede alterar o modificar una parte
# la unica opción para cambiar su contenido es cambiar todo el conteno

cadena = "Oste es un saludo Hola"

# Ejemplo con una tupla

tupla = (1, 0, 1, 1, 0, 1, 1)

# Intentar modificar un elemento de la tupla dará un error
#tupla[1] = 0  # Esto causará un error

#Opción cambiar el contenido commpleto de la tupla ya existente
# si en la posicion indice 1 esta la funcionalidad de llamadas salientes
# como los datos en las centrales celuulares son manejados de forma inmutable
# hayt que actualkizar todas las funcionalidades, conserava las que ya tiene
# y le pone 1 a la adiciuonal que desea que se habilite

tupla = (1, 1, 1, 1, 0, 1, 1)

"""Los números (int, float, complex) y los booleanos (bool) se consideran inmutables en Python porque una vez que se les asigna un valor, ese valor no puede cambiar. Si necesitas un valor diferente, debes crear un nuevo objeto en lugar de modificar el existente."""

# Ejemplo con números
numero = 10
print(f"Original: {numero}")

numero = 20  # Se crea un nuevo objeto
print(f"Nuevo: {numero}")


# Ejemplo con booleanos
booleano1 = True
print(f"Original: {booleano1}")

booleano1 = False  # Se crea un nuevo objeto
print(f"Nuevo: {booleano1}")

"""#**2 - TIPOS DE DATOS AVANZADOS EN PYTHON**

Existen tipos de datos más avanzados que permiten manejar estructuras de datos más complejas y realizar operaciones más sofisticadas. Aquí te dejo algunos de los tipos de datos avanzados más comunes:

**Tipos de Datos Avanzados en Python**
*   **Conjuntos (set):** Colecciones desordenadas de elementos únicos.

*   **Listas** por comprensión (list comprehensions): Sintaxis concisa para crear listas.
*   **Generadores** (generators): Funciones que permiten iterar sobre una secuencia de valores.
*   Decoradores (decorators): Funciones que modifican el comportamiento de otras funciones.
*   Clases y Objetos (OOP): Definición de tipos de datos personalizados mediante la programación orientada a objetos.
*   Módulos y Paquetes: Organización de código en archivos y directorios reutilizables.
*   Context Managers: Manejo de recursos como archivos y conexiones de manera eficiente.

*   Lista =  [ , ,  ]   con corchetes
*   tupla =  ( , , )    con parentesis curvo
*   cojunto = {  ,  ,  }  con llaves
"""

# Conjunto
# incia con llave de apertura y termina con llave de cierre
# los conjuntos no almacenas el orden de los elementos

conjunto_enteros = { 1, 2, 3, 4, 5 }
conjunto_materia = { "calculo","algebra lineal", "IA", "Prog Web"}
conjunto_alumnos = { "Fausto","Bernanrdo", "Santiago", "Daniela", "Ashile", "Estefany"}

# al imprimir un conjunto los elemantos pueden mostrarse en orden distinto
# porque el conjunto en Python es un s estructura de tipo hash (busquedas y peraciones rapidas)

print(conjunto_enteros)
print(conjunto_materia)
print(conjunto_alumnos)

print("")

print("Secuencia de numeros: " ,  conjunto_enteros)
print("Materias de Ing:" ,  conjunto_materia)
print("Alumnos del Curso:" ,  conjunto_alumnos)

# si se requiere conservar el orden de los elementos podemos usar listas
lista_materia = [ "calculo","algebra lineal", "IA", "Prog Web" ]

print(lista_materia)

# Para definir una funcion que ejecute una actividad especifica
# usamos la palabra reservada def

variable_g1 = 21

def nombre_funcion():
  variable_local_l1 = 3
  print("primera linea de la funcion")
  print("segunda linea de la funcion")
  print("tercera linea de la funcion")

x = 1

if x == 1:
  pass # Esto es un placeholder para el código que iría aquí
  pass

else:
  pass # Esto es un placeholder para el código que iría aquí
  pass

# La sintaxis de bucle for en Python es diferente a C++/Java
for x in range(1, 10):
  pass # Esto es un placeholder para el código que iría aquí
  pass


while x < 10:
  pass # Esto es un placeholder para el código que iría aquí
  pass
  x += 1 # Es importante modificar la condición para evitar un bucle infinito

#Metodo range para generar un rango de datos
range(5)

print(range(5))

# Definimos una función que genere 5 numeros enteros

def generador1_numeros():
    for elemento_range_ind in range(5):
        yield elemento_range_ind

generador1 = generador1_numeros()
print(f"Lista generada de forma automática: {list(generador1)}")

# Generador de n numeros enteros
n_elementos = 100

def generador2_n_numeros(n_elementos):
    for elemento_range_ind in range(n_elementos):
        yield elemento_range_ind

#variante para obtener la capcidad de devolver un valor al programa principal
#usando la palabra reservada yield (formateado como un elemento de lista)

generador2 = generador2_n_numeros( n_elementos )
print(f"Lista generada de forma automática: {list(generador2)}")

"""#**3 - Tipos de bloques de programación**

###En los lenguajes previos se ha manejado dos tipos de bloques
####1er - funciones       **Oracle**: funtion ,  **C++ java**  int funcionX() **
####2do - prodedimientos  **Oracle**: procedure, **C++ java**  void funcionX()  **

####**Las funciones se caracterizan por** ejecutar un número de líneas de código y al final **devolver un valor** al programa que invoco a la funcion

####**Los procedimientos se caracterizan por** ejecutar un número de líneas de código y al final **no devuelven un valor** al programa que invoco al procedimiento

##**3.1 - función en Python**
"""

# Creamos una función que sume dos numeros y me devuelva el resultado
# Posteriormente capturo el resultado en el programa principal e imprimo el resultado en pantalla
# Con la palabra reservada llamada return, devuelvo el valor resultante de la función

def operacion_de_suma(a, b):
    return a + b  # aqui devolvemos el valor

valor1 = 3
valor2 = 5
# invocamos a la función
resultado_de_suma = operacion_de_suma(valor1, valor2)

print(resultado_de_suma)  # Salida: 8
print(f"El resultado de la suma de {valor1} + {valor2} = {resultado_de_suma}")  # Salida: 8

"""##**3.2 - procedimiento en Python**"""

# Definimos un procedimiento

def operacion_de_suma_v2(a, b):
  resultado_v2 = a + b
  print("Resultado mostrado desde el interior de la función suma de a + b")
  print(f"Resultado de la suma de {a} + {b} = {resultado_v2} ")

valor3 = 6
valor4 = 10
# invocamos el procedimiento
operacion_de_suma_v2(valor3, valor4)

"""#**4 - Listas de listas, Diccionarios con listas, Datasets, Datasets de Pandas**

##**4.1 - Listas de Listas**

1. Creamos las listas simples individuales que va a ser contenidas
2. Creamos la lista de listas
"""

lista1_nombres_est = [ "Juan", "Alberto", "Maria", "Carlos"]
lista2_edades_est = [ 18, 19, 24, 35]
lista3_recidencia_est = [ "Guayaquil", "Babahoyo", "Salitre", "Salinas"]
lista4_semestre_est = [ 1, 6, 10, 3]

lista_estudiantes = [lista1_nombres_est, lista2_edades_est, lista3_recidencia_est, lista4_semestre_est ]

print(lista_estudiantes)

for cada_lista in lista_estudiantes:
  print(cada_lista)

contador = 1
for cada_lista in lista_estudiantes:
  print("Lista No. ", contador, ": ", cada_lista)
  contador = contador + 1

# Creando una lista de listas en  un paso

# Lista de listas definifas en un paso

Lista_de_lista2_alumnos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Juan", 30, "Guayaquil"],
    ["Ana", 25, "Quito"],
    ["Luis", 35, "Cuenca"]
]

for fila in Lista_de_lista2_alumnos:
    print(fila)

"""##**4.2 - Diccionario con listas**"""

# Creamos un diccionario simple
diccionario1_simple = {
    "Nombre": "Juan",
    "Edad": 30,
    "Ciudad": "Guayaquil"
}

# Creamos un diccionario con listas
diccionario2_con_listas = {
    "Nombre": ["Juan", "Ana", "Luis"] ,
    "Edad":    [30, 25, 35]  ,
    "Ciudad": ["Guayaquil", "Quito", "Cuenca"]
}

for clave_i, valores_i  in diccionario2_con_listas.items():
  print(f"{clave_i} : {valores_i}")

"""#**5 - Desafio**"""

#Desarrolle un programa que permita mostrar los datos de cada estuduante
#con el formato siguiente en la salida a pantalla
# Elemento n: El alumno "Nombre" posee "edad" años y reside en "Ciudad"

# Paso 1 - capruro el tamaño de la lista
Num_elementos_lista = len(diccionario2_con_listas["Nombre"])

print(Num_elementos_lista)

range(Num_elementos_lista)

for i in range(Num_elementos_lista):
  nombre_i = diccionario2_con_listas["Nombre"][i]
  edad_i = diccionario2_con_listas["Edad"][i]
  ciudad_i = diccionario2_con_listas["Ciudad"][i]

  #print(f" {nombre_i} posee {edad_i} años y vive en {ciudad_i}.")
  #mensaje para un desarrollador
  print(f"Indice {i}: {nombre_i} posee {edad_i} años y vive en {ciudad_i}.")

for i in range(Num_elementos_lista):
  nombre_i = diccionario2_con_listas["Nombre"][i]
  edad_i = diccionario2_con_listas["Edad"][i]
  ciudad_i = diccionario2_con_listas["Ciudad"][i]

  #mensaje para un usuario final
  print(f"Posición {i+1}: {nombre_i} posee {edad_i} años y vive en {ciudad_i}.")