# -*- coding: utf-8 -*-
"""TALLER 03 - Introducción a Dataframes de Pandas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrAnfeKAWuXIuS_1-DbBIAWLP-PRylE7

# **TALLER 03 - Introducción a Dataframes de Pandas**

####**Docente:** Ing. Ivan Acosta, Mgs.
####**Nivel:** Ingeniería
####**Materia:** Programación Avanzada
####**Lenguaje**: Python

**El Problema**

Se aborda es la necesidad de procesar datos brutos, que a menudo contienen valores faltantes, para prepararlos para un análisis posterior o para alimentar modelos de aprendizaje automático.

**Objetivo General**

Introducir y aplicar técnicas de manipulación y preprocesamiento de datos utilizando la librería Pandas en Python, centrándose en la gestión y tratamiento de valores faltantes.

**Objetivos Específicos:**

1.  Cargar y explorar datos: Aprender a cargar un conjunto de datos desde un archivo CSV en un DataFrame de Pandas y realizar una exploración inicial para comprender su estructura, tipos de datos y la presencia de valores faltantes.

2.  Subseleccionar información de DataFrames: Desarrollar habilidades para extraer subconjuntos específicos de datos de un DataFrame, ya sea por filas, columnas o rangos, utilizando métodos como `iloc`.

3.  Tratar valores faltantes (Missing Values): Dominar diferentes estrategias para imputar valores faltantes en variables numéricas, incluyendo el uso de la media, la mediana, la moda y valores constantes.

**Objetivos de Aprendizaje:**

Al completar este cuaderno, los estudiantes o usuarios serán capaces de:
*   Familiarizarse con el tipado dinámico en Python y la importancia de las librerías para la ciencia de datos.
*   Utilizar librerías como Pandas y Scikit-learn para la carga, exploración y manipulación de datos.
*   Aplicar técnicas de subselección para acceder a partes específicas de un DataFrame.
*   Identificar y tratar valores faltantes en conjuntos de datos numéricos mediante técnicas de imputación basadas en la media, mediana, moda y valores constantes.
*   Preparar un conjunto de datos "crudo" para su análisis o modelado.

#**0 - Tipado dinamico**
"""


"""#**1 - Librerias en Python**"""

# Cargamos una libreria empleamos la palabra import
import numpy as np   # series

# permite manejar de forma avanzada una colección de datos, similar a tener una tabla de base de datos
import pandas as pd  # datafames

# Librería para manejar gráficos en Python
import matplotlib as plt
import seaborn as sns
import os

# Creamos variables de diferentes tipos de datos para mostrar el tipado dinámico de Python

variable1 = 1

variable2 = 2.6

variable3 = "Hola"

variable4 = 'C'

variable5 = True

variable6 = 'Hola'

variable7 = "22"

print(f"variable1 con valor {variable1} de tipo: " , type(variable1))
print(f"variable2 con valor {variable2} es de tipo: " , type(variable2))
print(f"variable3 con valor {variable3} es de tipo: " , type(variable3))
print(f"variable4 con valor {variable4} es de tipo: " , type(variable4))
print(f"variable5 con valor {variable5} es de tipo: " , type(variable5))
print(f"variable6 con valor {variable6} es de tipo: " , type(variable6))
print(f"variable7 con valor {variable7} es de tipo: " , type(variable7))

variable1 = 8.3
print(f"variable1 con valor {variable1} de tipo: " , type(variable1))

variable1 = "Bienvenidos"
print(f"variable1 con valor {variable1} de tipo: " , type(variable1))


"""#**2 - Creamos carpetas mediante uso de comandos de Sistema Operativco (multiplataforma)**"""

# Creamos la carpeta 'datos' de forma multiplataforma (Windows, Linux, macOS)

os.makedirs("datos", exist_ok=True)  # exist_ok=True evita error si ya existe
print("Carpeta 'datos' creada o ya existente.")

# Para borrar la carpeta se puede usar:
# import shutil; shutil.rmtree("datos")

"""#**3 - Lectura de datos en una archivo CSV (Valores separados por comas)**"""

obj_dataframe_datos  = pd.read_csv("https://raw.githubusercontent.com/ivanacostag02/software_y_base_de_datos/refs/heads/main/datos/01_Data.csv")

type(obj_dataframe_datos)

"""#**4 - Exploracion de los datos**

##**4.1 -Visualizamos los primeros y últimos registros**
"""

# Visualizamos los primeros registros grabados en el archivo usando el metodo head(x)
obj_dataframe_datos.head(5)

# Visualizamos los últimos registros grabados en el archivo usando el metodo head(x)
obj_dataframe_datos.tail(4)

"""##**4.2 - Visualizamos la estructura del Dataframe creado con Pandas pd**"""

# Visualizamos los últimos registros grabados en el archivo usando el metodo head(x)

obj_dataframe_datos.info()

obj_dataframe_datos.head(3)

obj_dataframe_datos.columns

obj_dataframe_datos.describe()

obj_dataframe_datos.describe().round(2)

###  Índice
###    0      1     2      3
### Country  Age Salary Purchased

"""##**4.3 - Extracción de un sub conjunto de datos del Dataframe**"""

# para  df.iloc[                          ]
#            df.iloc[ idx_fila_inc: idx_fila_parada , idx_col_ini: idx_col_parada ]

# Meta: Extraer los datos de
#                        Desde la 3ra fila hasta la 5ta fila
#                      y 2da columna a 3ra columna

obj_dataframe_datos.iloc[  2  :  5  ,   1 : 3   ]

# Meta2: Recupere todos los datos de su dataframe
obj_dataframe_datos.iloc[    :     ,     :     ]

# Meta2: Recupere todos los datos de su dataframe
obj_dataframe_datos.iloc[    :     ,  0  :  4   ]

# Meta3: Recupere los datos de todas las filas y solo la última columna
# Cuando recupera una única columna debe darle el índice exacto de
# esa columna

#obj_dataframe_datos.iloc[    :     ,  3  ]
obj_dataframe_datos.iloc[  :  ,3  ]

# Misión 4: Recuperar la septima fila con todas las columnas
obj_dataframe_datos.iloc[  6  , :  ]

# Capturamos los datos de la variable de investigación
# Variable y, dependiente, a predecir, objeto de su estudio

y = obj_dataframe_datos.iloc[  :  , 3  ]

# capturamos los datos de la última columna indepentnte del tamaño del dataframe
y = obj_dataframe_datos.iloc[  :  , -1  ]

# Capturamos los datos de la variable inddependientes de investigación
# Variable Xs, independiente, predectoras, son las que afectas a la variable 'y'
# Meta2: Recupere todos los datos de su dataframe

Xs = obj_dataframe_datos.iloc[    :     ,  0  :  -1   ]

print(Xs)

print(y)

type(Xs)

type(y)

# Misión 4: Recuperar la septima fila con todas las columnas
obj_dataframe_datos.iloc[  6  , :  ]

# Misión 4: Recuperar la septima fila con todas las columnas
fila = obj_dataframe_datos.iloc[  6  , :  ].transpose()
horizontal_output = ' '.join(map(str, fila))
print(horizontal_output)

#presentar la fila recuperada con los nombres de los campos
print(fila.to_frame().T)

"""##**4.4 - Series en Pandas**

Una Serie de Pandas es una estructura de datos unidimensional etiquetada que puede contener datos de cualquier tipo, como enteros, flotantes, cadenas y objetos de Python.
"""

import pandas as pd

# Crear una lista de datos
lista_data = [10, 20, 30, 40, 50]

# Crear una Serie de Pandas
serie_datos = pd.Series(lista_data)

print(serie_datos)

type(serie_datos)

print(lista_data)

print(lista_data[0])

print(lista_data[-1])

print(lista_data[-2])

print(lista_data[-3])

print(serie_datos)

serie_datos[0]

serie_datos[4]

serie_datos[len(serie_datos)-1]

"""#**5 - Tratamiento de missing values, valores perdidos, valores vacios**

##**5.1 - Imputando las variables independientes (Xs) mediante la formula del promedio**
"""

Xs.info()

# importar librerias para realizar el proceso
import numpy as np
from sklearn.impute import SimpleImputer

# veririficamos la versión
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "show", "scikit-learn"])

# Verificamos las versiones de librerias que estamos usando en nuestro proyecto
import sklearn
sklearn.show_versions()

# Verificamos la versión dfe sklear que estamos usando en nuestro entorno
import sklearn
print(sklearn.__version__)

from re import VERBOSE
obj_imputador = SimpleImputer( missing_values = np.nan , strategy='mean')

# Accediendo a una columna a atravez de el nombre de la variable
Xs["Age"]

# Accediendo a una columna a atravez de el nombre de la variable
Xs["Salary"]

# Usamos una lista con los de nombres de las columnas, para acceder a varias columnas a la vez
Xs[ ["Age", "Salary"] ]

# Generamos un objeto entrenado con los promedios y desviaciones estandar de las variables
# Age y Salary, creamos y entrenamos al objeto imputador_de_numeros

obj_imp_numeros = obj_imputador.fit(Xs[ ["Age", "Salary"] ])

# Utilizamos el objeto imputador de numeros para imputar el datafrae de las Xs
# Xs son las variables independienets del proyecto de investigación

Xs[ ["Age", "Salary"] ] = obj_imp_numeros.transform(Xs[ ["Age", "Salary"] ])

# Mostamos el contenido del Dataframe ya imnputado
print(Xs)

"""##**5.2 - Desafio: Realizar la imputación empleando la formula estadistica de la mediana**"""

#Desafio resuelto con la Mediana

# importar librerias para realizar el proceso

# import numpy as np
# from sklearn.impute import SimpleImputer

Xs_ver_mediana = obj_dataframe_datos.iloc[    :     ,  0  :  -1   ]

from re import VERBOSE
obj_imputador = SimpleImputer( missing_values = np.nan , strategy='median')

# Generamos y entrenamos un objeto con la moda
# Age y Salary

obj_imp_numeros = obj_imputador.fit(Xs_ver_mediana[ ["Age", "Salary"] ])

Xs_ver_mediana[ ["Age", "Salary"] ] = obj_imp_numeros.transform(Xs_ver_mediana[ ["Age", "Salary"] ])

# Dataframe de Xs impuatda con la mediana de cada columna
Xs_ver_mediana



"""##**5.3 - Desafio: Realizar la imputación empleando la formula estadistica de la moda**"""

# importar librerias para realizar el proceso

# import numpy as np
# from sklearn.impute import SimpleImputer

Xs_impu_moda = obj_dataframe_datos.iloc[    :     ,  0  :  -1   ]

print(Xs_impu_moda)

# from re import VERBOSE
obj_imputador = SimpleImputer( missing_values = np.nan , strategy='most_frequent')

# Generamos y entrenamos un objeto con la moda
# Age y Salary

obj_imp_numeros_vmoda = obj_imputador.fit(Xs_impu_moda[ ["Age", "Salary"] ])

Xs_impu_moda[ ["Age", "Salary"] ] = obj_imp_numeros_vmoda.transform(Xs_impu_moda[ ["Age", "Salary"] ])

print(Xs_impu_moda)



"""##**5.4 - Desafio: Realizar la imputación empleando un valor constante**"""

#Capturo los datos de las variables X del dataframe original
Xs_impu_con_constante = obj_dataframe_datos.iloc[    :     ,  0  :  -1   ]

print(Xs_impu_con_constante)

# from sklearn.impute import SimpleImputer
# import numpy as np

# Definimos los valores constantes a utilizar en cada columna
# usamos un objeto tipo diccionario para guardar nuestros datos en estructura clave: valor

dic_datos_usar = {
    "Age": 30,         # valor para imputar las edades faltantes
    "Salary": 50000    # valor para imputar los sueldos faltantes
}

dic_datos_usar

# Crear imputadores para cada columna

for nombre_de_lista in ["Age", "Salary"]:

  obj_imputador_desafio4 = SimpleImputer( missing_values=np.nan, strategy="constant" , fill_value = dic_datos_usar[nombre_de_lista])
  Xs_impu_con_constante[nombre_de_lista] = obj_imputador_desafio4.fit_transform(Xs_impu_con_constante[[nombre_de_lista]])

print(Xs_impu_con_constante)