# -*- coding: utf-8 -*-
"""TALLER 04 - Datos Avanzados - Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSMwRALuSqJVVZLbewcK7Tf9T1CxYxOq

#**TALLER 04 - Tipos de Datos Avanzados: SET**

####**Docente:** Ing. Ivan Acosta, Mgs.
####**Nivel:** Ingeniería
####**Materia:** Programación Avanzada
####**Lenguaje**: Python

### **El Problema**
En el procesamiento y la gestión de datos, a menudo es necesario trabajar con colecciones de elementos únicos y realizar operaciones para identificar elementos comunes, elementos distintos o combinar estas colecciones de manera eficiente.

### **Objetivo General**
Comprender y aplicar los conceptos fundamentales de los conjuntos (sets) en Python para la gestión de colecciones de datos únicos y la realización de operaciones lógicas entre ellos.

### **Objetivos Específicos**

1.  **Creación y Manipulación Básica**: Aprender a crear conjuntos en Python y a añadir o eliminar elementos, comprendiendo la naturaleza no ordenada y de elementos únicos de los sets.

2.  **Operaciones de Conjuntos (Intersección)**: Aplicar la operación de intersección para encontrar elementos comunes entre dos o más conjuntos, utilizando tanto el método `.intersection()` como el operador `&`.

3.  **Operaciones de Conjuntos (Diferencia y Unión)**: Utilizar las operaciones de diferencia (`.difference()` o `-`) para identificar elementos únicos en un conjunto respecto a otro, y las operaciones de unión (`.union()` o `|`) y actualización (`.update()`) para combinar conjuntos.

### **Objetivos de Aprendizaje**

Al finalizar este taller, el estudiante será capaz de:
*   Definir qué es un `set` en Python y cuándo es apropiado utilizarlo para resolver problemas específicos.
*   Crear conjuntos y manipular sus elementos (añadir, eliminar) de manera efectiva.
*   Realizar operaciones de intersección (`intersection()` o `&`) entre conjuntos para encontrar elementos compartidos.
*   Realizar operaciones de diferencia (`difference()` o `-`) entre conjuntos para identificar elementos exclusivos.
*   Realizar operaciones de unión (`union()` o `|`) y actualización (`update()`) entre conjuntos para combinarlos.
*   Aplicar `sets` para resolver problemas prácticos como la identificación de usuarios con múltiples perfiles, la gestión de listas únicas o la consolidación de grupos.

**Set:** Conjuntos de datos no ordenados y unicos.

##**1.1 - Creamos dos sets de frutas**
"""

# Creamos dos objetos de tipo sets
obj_set_frutas          = { "manzana"  , "naranja"   , "plátano"   , "pera"  , "uva", "limón" }
obj_set_frutas_citricas = { "toronja", "naranja", "limón", "lima"  }

print(obj_set_frutas)

print(obj_set_frutas_citricas)

#Agreamos un tipo de fruta adicional al conjunto o set
obj_set_frutas.add("sandía")

print(obj_set_frutas)

obj_set_frutas_comunes =  obj_set_frutas.intersection(obj_set_frutas_citricas)

print(obj_set_frutas_comunes)

"""##**1.2 - Creamos dos sets de personas**"""

# Ejercicio #2

obj_set_usuarios_perfil_consulta =  { "Ana" , "Juan" , "Carlos" , "Ashley", "Carolina" }
obj_set_usuarios_perfil_developer = { "Cesar", "Dennisse", "Jorge", "Juan", "Ashley" }
obj_set_usuarios_perfil_admin =     { "Ashley" }

# Encontrar los usuarios que poseen perfil para consultar y para modificar
# obj_set_xxxxx.intersection(obj_set_yyyy)

obj_set_colegas_consultan_modifican = obj_set_usuarios_perfil_consulta.intersection(obj_set_usuarios_perfil_developer)

print(obj_set_colegas_consultan_modifican)

"""##**1.3 - Encontrar los usuarios que poseen perfil para consultar y a la vaz son Administradores**"""

# Encontrar los usuarios que poseen perfil para consultar y a al vez son Administradores de sistema
# obj_set_xxxxx.intersection(obj_set_yyyy)

obj_set_colegas_consultan_admin = obj_set_usuarios_perfil_consulta.intersection(obj_set_usuarios_perfil_admin)

print(obj_set_colegas_consultan_admin)

# Encontrar los usuarios que poseen perfil para consultar y a la vez son Administradores de sistema
# usando el simbolo amperson  &  signofoca la 'y' del ingles

obj_set_colegas_comunes = obj_set_usuarios_perfil_consulta & obj_set_usuarios_perfil_developer

obj_set_colegas_comunes

"""##**1.4 - # Encontrar los usuarios que poseen perfil para developer y son Administradores**"""

# Encontrar los usuarios que poseen perfil para developer y son Administradores de sistema
# usando el simbolo amperson  &  signofoca la 'y' del ingles

obj_set_consultan_admin_v2 =  obj_set_usuarios_perfil_developer & obj_set_usuarios_perfil_admin

obj_set_consultan_admin_v2

# Busque los usuarios que no son comunes

"""obj_set_usuarios_perfil_consulta =  { "Ana" , "Juan" , "Carlos" , "Ashley", "Carolina" }
obj_set_usuarios_perfil_developer = { "Cesar", "Dennisse", "Jorge", "Juan", "Ashley" }
obj_set_usuarios_perfil_admin =     { "Ashley" }

##**1.5 - Buscamos los ususarios que solo pueden consultar**
"""

# Buscamos los ususarios que solo pueden consultar ( y no son developer)
# Usando el metodo difference

obj_set_solo_consultan = obj_set_usuarios_perfil_consulta.difference(obj_set_usuarios_perfil_developer)

obj_set_solo_consultan

# Buscamos los ususarios que solo pueden consultar
# Usando el operador '-'
obj_set_solo_consultan_v2 = obj_set_usuarios_perfil_consulta - obj_set_usuarios_perfil_developer

"""En los lenguajes orientados a objetos (POO: Python, C, Java) un operador (ej: + ,  - ) puede compmportarse de manera distinta, dependiendo de los elementos que le entregamos para que ejecute su trabajo, esa capacidad se conoce como Sobrecarga"""

obj_set_solo_consultan_v2

"""##**1.6 - Encuentre los usuarios developers que no pueden consultar**"""

# Encuentre los usuarios developers que no pueden consultar

obj_set_solo_deleoper_v2 = obj_set_usuarios_perfil_developer - obj_set_usuarios_perfil_consulta

obj_set_solo_deleoper_v2

"""##**1.7 - Desafio: Unir dos subconjuntos para ampliar el numero de Administradores**"""

# Escenario: Comprado más servisores y se necesita más adminstradores para distribuir
# el trabajo de el mantenimiento preventido de los servidores

# Encuentre los usuarios que estan solo como developers
#                  es decir no consultan y no son admin
# unalos al grupo de usuarios administradores

obj_set_usuarios_perfil_consulta =  { "Ana" , "Juan" , "Carlos" , "Ashley", "Carolina" }
obj_set_usuarios_perfil_developer = { "Cesar", "Dennisse", "Jorge", "Juan", "Ashley", "Alberto", "Peter" }
obj_set_usuarios_perfil_admin =     { "Ashley", "Carolina", "Pierina" }

# Tomo el conjunto developers y le retiro aquellos que consultan, luego tomo el resultado y le retiro aquellos quye son Admin
obj_set_solo_developers = obj_set_usuarios_perfil_developer - obj_set_usuarios_perfil_consulta - obj_set_usuarios_perfil_admin

obj_set_solo_developers

# Uno los usuarios solo_debvelopers al conjunto de administradores
obj_set_usuarios_perfil_admin.update(obj_set_solo_developers)

# Muestro el resultado de interates de set (conjunto) administradores
print("Usuarios administradores actualizados: \n", obj_set_usuarios_perfil_admin)