# -*- coding: utf-8 -*-
"""TALLER 02 - Entrada y Salida a travez de Archivos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gyz0avnlU5k5UNyCtMP4LtzYgwf0D1fg

#**TALLER_02 - Ingreso de datos desde el teclado**

####**Docente:** Ing. Ivan Acosta, Mgs.
####**Nivel:** Ingeniería
####**Materia:** Programación Avanzada
####**Lenguaje**: Python

### **El Problema**

El manejo de datos mediante el ingreso de información a través del teclado y la interacción con archivos de texto es una habilidad fundamental en la programación. Sin embargo, los principiantes a menudo enfrentan desafíos para comprender cómo capturar, procesar y almacenar datos de manera efectiva, lo que puede limitar su capacidad para desarrollar aplicaciones interactivas y persistentes.

### **Objetivo General**

Desarrollar la capacidad de los estudiantes para interactuar con el usuario y con el sistema de archivos, mediante la implementación de operaciones básicas de entrada/salida de datos en Python.

### **Objetivos Específicos**

1.  **Captura de Datos:** Implementar código para solicitar y recibir información numérica y textual del usuario a través del teclado.
2.  **Manejo Básico de Archivos:** Abrir, leer y escribir datos en archivos de texto, utilizando diferentes modos de acceso (lectura, escritura y adición).
3.  **Gestión de Múltiples Datos:** Aplicar técnicas para almacenar y recuperar varias líneas de texto en un archivo de manera eficiente.

### **Objetivos de Aprendizaje**

Al finalizar este ejercicio, el estudiante será capaz de:

*   Utilizar la función `input()` para obtener datos del usuario.
*   Convertir tipos de datos de entrada (por ejemplo, de cadena a entero) según sea necesario.
*   Abrir y cerrar archivos de texto utilizando el contexto `with open(...)`.
*   Leer el contenido de un archivo línea por línea o en su totalidad.
*   Escribir nuevas líneas o sobrescribir el contenido de un archivo.

##**Capture dos datos numericos desde el teclado y presentacion en pantalla de la suma de los datos**
"""

# Instalación de la librería requests
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "install", "requests"])

try:
    numero1 = int(input("Digita un numero entre 1 a 30: "))
    numero2 = int(input("Digite su edad entre 1 y 110 años: "))
except ValueError:
    print("Error: debe ingresar valores numéricos enteros. Se usarán 0 por defecto.")
    numero1, numero2 = 0, 0

suma_num1_num2 = numero1 + numero2
print("La suma de los numeros es:", suma_num1_num2)

print(f'La suma de el número {numero1} + {numero2} es:', suma_num1_num2)

"""#**Operaciones de entrada y salida desde un archivo.txt**"""

# Paso 0 identificar la ruta donde esta el archivo
import os
import requests


# Usamos la ubicación del script como base para rutas absolutas
script_dir = os.path.dirname(os.path.abspath(__file__))
local_file_path = os.path.join(script_dir, "refranes.txt")
fuente_local   = os.path.join(script_dir, "datos", "Refranes.txt")

# Paso 1 abrir el archivo, en modo lectura ('r'  read)

url = "https://raw.githubusercontent.com/ivanacostag02/software_y_base_de_datos/refs/heads/main/datos/Refranes.txt"

try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()  # Lanza una excepción para códigos de estado de error (4xx o 5xx)

    # Decodificar el contenido y dividirlo en líneas
    lines = response.text.splitlines()

    print(f"Contenido del archivo desde la URL ({url}):")
    for line in lines:
        print(line)

    # Guardar el contenido en un archivo local
    with open(local_file_path, 'w', encoding='utf-8') as f:
        f.write(response.text)
    print(f"\nContenido guardado en archivo local: {local_file_path}")

except requests.exceptions.RequestException as e:
    print(f"Error al intentar acceder a la URL: {e}")
    print(f"Usando archivo fuente local: {fuente_local}")
    try:
        with open(fuente_local, 'r', encoding='utf-8') as f_in:
            contenido = f_in.read()
        with open(local_file_path, 'w', encoding='utf-8') as f_out:
            f_out.write(contenido)
        print(f"Archivo copiado desde '{fuente_local}' a '{local_file_path}'")
    except FileNotFoundError:
        print(f"Error: no se encontró el archivo fuente '{fuente_local}'")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

# Misión: Guarde 2 refranes adicionales uno por uno
# usanmos 'a' para append o adicionar infomación al final del archivo LOCAL

with open(local_file_path, 'a', encoding='utf-8') as archivo:

  # Aseguramos un salto de línea si el archivo no termina con uno
  # y luego añadimos los nuevos refranes.
  # Si no hay salto de línea, se añadirán al final de la última línea.
  # Para este ejemplo, añadiremos un salto de línea explícito.

  nueva_linea = "\n7 - Quien juega con fuego, sale quemado"
  archivo.write(nueva_linea)

  nueva_linea = "\n8 - A buen entendedor, pocas palabras"
  archivo.write(nueva_linea)

# Misión: Lea los refranes del archivo LOCAL de refranes.txt

with open(local_file_path, 'r', encoding='utf-8') as archivo:
  # recupera línea por línea y muestrala en pantalla

  for linea in archivo:
    print(linea.strip()) # .strip() para eliminar saltos de línea adicionales

# Misión: Guarde 3 refranes adicionales en una sola instrucción en el archivo LOCAL
# usanmos 'a' para append o adicionar infomación al final del archivo

with open(local_file_path, 'a', encoding='utf-8') as archivo:
  varias_lineas = [
      "\n9 - Más vale perder un minuto en la vida, que la vida en un minuto",
      "\n10 - El vivo vive del tonto, y el tonto de su trabajo",
      "\n11 - A la tercera va la vencida"
      ]
  archivo.writelines(varias_lineas)

# Misión: Lea los refranes del archivo LOCAL de refranes.txt

with open(local_file_path, 'r', encoding='utf-8') as archivo:
  # recupera línea por línea y muestrala en pantalla

  for linea in archivo:
    print(linea.strip()) # .strip() para eliminar saltos de línea adicionales

# Verificamos que un archivo que se abre con 'w' se escribe desde cero
# o se crea el contenido desde la primera línea
# Esto se hará en el archivo LOCAL

with open(local_file_path, 'w', encoding='utf-8') as archivo:

  nueva_linea = "12 - Mas vale pajaro, en mano que 100 volando\n"
  archivo.write(nueva_linea)

  nueva_linea = "13 - El que madruga, Dios lo ayuda\n"
  archivo.write(nueva_linea)

# Misión: Lea los refranes del archivo LOCAL de refranes.txt

with open(local_file_path, 'r', encoding='utf-8') as archivo:
  # recupera línea por línea y muestrala en pantalla

  for linea in archivo:
    print(linea.strip()) # .strip() para eliminar saltos de línea adicionales