# -*- coding: utf-8 -*-
"""TALLER 05 - Sentencias de Control Secuencial if y Repetitivo for y while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135Reav74JhUz39YqydrXm0NG9uCYGpRS

#**TALLER 05 - Sentencia de Control Secuenciales y Repetitivas**

####**Docente:** Ing. Ivan Acosta, Mgs.
####**Nivel:** Ingeniería
####**Materia:** Programación Avanzada
####**Lenguaje**: Python

**El Problema**

El ingeniero de software en la actualidad debe dominar las estructuras de control (if, for, while) y el uso de funciones en Python para poder construir programas claros, reutilizables y capaces de resolver problemas reales de forma estructurada.

**Objetivo General**

Aplicar sentencias de control secuenciales, condicionales e iterativas, junto con funciones en Python, para resolver problemas simples de cálculo, clasificación y automatización de tareas.

**Objetivos Específicos**

Implementar programas secuenciales que realicen cálculos básicos (áreas, promedios, mínimos, máximos y amplitud) a partir de datos numéricos.

Utilizar sentencias condicionales if, elif, else para tomar decisiones y clasificar información con base en reglas de negocio (por ejemplo, rangos de notas o tipos de producto).

Emplear bucles for y while para generar y recorrer secuencias, procesar listas y controlar ciclos de interacción (como conteos regresivos o juegos de adivinanza).

**Objetivos de Aprendizaje**

Escribir código en Python que combine operaciones secuenciales, condicionales y repetitivas de forma coherente.

Diseñar soluciones que recorren colecciones de datos (listas) y aplican transformaciones paso a paso.

Encapsular lógica en funciones que devuelven uno o varios resultados y reutilizarlas en diferentes partes de un programa.

##**1.1 - Sentencias Secuenciales**
"""

# Creamos un bloque de código secuencial
# que permita calcular el área de un rectangulo

# Unidades en cm

# Parte 1 - Entrada de datos
base = 5
altura = 10

# Parte 2 - Procesamiento (Transformación)
area = base * altura

# Parte 3 - Salida del sistema
print(area)

# Creamos un bloque de código secuencial
# que permita calcular el área2 de un rectangulo

# Unidades en cm

# Parte 1 - Entrada de datos
alto = 7
ancho = 11

# Parte 2 - Procesamiento (Transformación)
area2 = alto * ancho

# Parte 3 - Salida del sistema
print(area2)

# Creamos un bloque de código secuencial
# que permita calcular el área3 de un rectangulo

# Unidades en cm

# Parte 1 - Entrada de datos
lado1 = 8
lado2 = 4

# Parte 2 - Procesamiento (Transformación)
area3 = lado1 * lado2

# Parte 3 - Salida del sistema
print(area3)

## Se poseen lecturas de temperaturas recopiladas en el mes y se le pide que realice un análisis de los datos
lista_temperaturas = [ 22 , 24 , 19 , 21 , 18, 25, 20]

"""Obtenga la Cantidad de datos recopilados"""

cantidad_elementos = len(lista_temperaturas)



print("Cantidad de datos: ", cantidad_elementos)

"""Obtenga la Sumatoria de temperaturas de la semana"""

sumatoria = sum(lista_temperaturas)

"""Calcule el promedio de temperaturas de la semana"""

promedio_de_temperatura  = sumatoria / cantidad_elementos
print(promedio_de_temperatura)

"""Obtenga el valor más pequeño disponible en sus datos"""

mas_pequeño = min(lista_temperaturas)
print(mas_pequeño)

mas_grande = max(lista_temperaturas)
print(mas_grande)

"""Encuentre la amplitud de las temperaturas"""

amplitud_temperaturas = mas_grande - mas_pequeño
amplitud_temperaturas

"""##**1.2 - Sentencias de control Secuencial**

###**1.2.1 - Con if - Verifique si un estudiante aprueba o reprueba una materia**
"""

Nota = 5.5

if Nota >= 7.0:
  mensaje_alumno = "Aprobado"
else:
  mensaje_alumno = "Reprobado"

print(f"El estudiante ha {mensaje_alumno} con la nota de {Nota}")

Nota = 8.5

if Nota >= 7.0:
  mensaje_alumno = "Aprobado"
else:
  mensaje_alumno = "Reprobado"

print(f"El estudiante ha {mensaje_alumno} con la nota de {Nota}")

"""###**1.2.2 - Con if-esle - Verifique que categorÍa de producto esta adquiriendo un cliente y otorgue un descuento diferenciado**"""

# $1 a $19.99   Economico
# $20 a $49.99  Estándar
# $50 a $99.99  Premium
# $100 o mas    Lujo

precio = 75

# Prompt #1:
# crea una setencia if else anidad en la cual se valide los siguientes rangos
# de precios de una variable precio y envia a pantalla un mensaje
# los rangos a validar son "
# $1 a $19.99   Economico
# $20 a $49.99  Estándar
# $50 a $99.99  Premium
# $100 o mas    Lujo"

precio = 75

if precio >= 1 and precio <= 19.99:
  print("Economico")
elif precio >= 20 and precio <= 49.99:
  print("Estándar")
elif precio >= 50 and precio <= 99.99:
  print("Premium")
elif precio >= 100:
  print("Lujo")
else:
  print("Precio fuera de rango")

# Prompt #2:
# Crea una setencia if else anidada en la cual se valide los siguientes rangos
# de precios de una variable precio y captura en una variable categoria
# el mensaje de texto del tipo de rango de ese precio, los rangos a validar son "
# $1 a $19.99   Economico
# $20 a $49.99  Estándar
# $50 a $99.99  Premium
# $100 o mas    Lujo"

precio = 75  # Ejemplo de precio

if precio >= 1 and precio <= 19.99:
  categoria = "Económico"
elif precio >= 20 and precio <= 49.99:
  categoria = "Estándar"
elif precio >= 50 and precio <= 99.99:
  categoria = "Premium"
elif precio >= 100:
  categoria = "Lujo"
else:
  categoria = "Precio fuera de rango"

print(f"Para un precio de ${precio}, la categoría es: {categoria}")



"""###**1.2.3 - Sentencia de Control Repetitivo: for**"""

# prompt: Generar una lista de numeros enteros del 1 al 5, y guardarlos en la variable lista_enteros, con un lazo for calcular el cuadrado de cada uno de los elementos de la lista, finalmente guardar el tresultado en una nueva lista de lista_enteros_al_cuadrado, Presenta al final los valotres calculados guardados en la listad de valores al cuadrado

# Generar una lista de números enteros del 1 al 5
lista_enteros = list(range(1, 6))

# Inicializar una lista vacía para almacenar los cuadrados
lista_enteros_al_cuadrado = []

# Calcular el cuadrado de cada elemento usando un bucle for
for numero in lista_enteros:
  cuadrado = numero ** 2
  lista_enteros_al_cuadrado.append(cuadrado)

# Presentar los valores calculados
print("Valores al cuadrado:", lista_enteros_al_cuadrado)

# prompt: Generar una lista de numeros enteros del 1 al 5, y guardarlos en la variable lista_enteros, con un lazo for calcular el cuadrado de cada uno de los elementos de la lista, finalmente guardar el tresultado en una nueva lista de lista_enteros_al_cuadrado, Presenta al final los valotres calculados guardados en la listad de valores al cuadrado

# Generar una lista de números enteros del 1 al 5
lista_enteros = list(range(1, 6))

# Inicializar una lista vacía para almacenar los cuadrados
lista_enteros_al_cuadrado = []

# Calcular el cuadrado de cada elemento usando un bucle for
for numero in lista_enteros:
  cuadrado = numero ** 2
  lista_enteros_al_cuadrado.append(cuadrado)

# Presentar los valores calculados
print("Valores al cuadrado:", lista_enteros_al_cuadrado)

# prompt: Generar una lista de numeros enteros del 1 al 100,
# y guardarlos en la variable lista_enteros, con un lazo for calcular el cuadrado de cada uno de los elementos de la lista, finalmente guardar el tresultado en una nueva lista de lista_enteros_al_cuadrado, Presenta al final los valotres calculados guardados en la listad de valores al cuadrado

# Generar una lista de números enteros del 1 al 100
lista_enteros = list(range(1, 101))

# Inicializar una lista vacía para almacenar los cuadrados
lista_enteros_al_cuadrado = []

# Calcular el cuadrado de cada elemento usando un bucle for
for numero in lista_enteros:
  cuadrado = numero ** 2
  print(f"El cuadrado de {numero} es {cuadrado}")
  lista_enteros_al_cuadrado.append(cuadrado)

# Presentar los valores calculados
print("Valores al cuadrado:", lista_enteros_al_cuadrado)

# prompt: Empleando el lazo while genera una secuancia decendente de 10 elemento similar a la que se emplea cuando va a despegar una nava espacial, en la salida necesitamos ver los mensajes del contero regresivo de cada elemento, y al final muestra un mensaje que diga "Despegue".  emplea range para generar la secuencia descendente a usar.

# Secuencia descendente para el despegue
for i in range(10, 0, -1):
  print(i)

print("Despegue")

# prompt: Empleando el lazo while genera una secuancia decendente de 30 elementos
# con saltos de 3 en 3
# similar a la que se emplea cuando va a despegar una nava espacial, en la salida necesitamos ver los mensajes del contero regresivo de cada elemento, y al final muestra un mensaje que diga "Despegue".  emplea range para generar la secuencia descendente a usar.

# Secuencia descendente para el despegue
for i in range(30, 0, -3):
  print(i)

print("Despegue")

"""###**1.2.4 - Sentencia de control repetitivo while**"""

# prompt: Empleando la sentencia de control while genera una secuencia decendente de 10 elemento similar a la que se emplea cuando va a despegar una nava espacial, en la salida necesitamos ver los mensajes del contero regresivo de cada elemento, y al final muestra un mensaje que diga "Despegue".  emplea range para generar la secuencia descendente a usar. Valida al inicio que aun existan elementos de la secuencia antes de salir del while

# Secuencia descendente para el despegue usando while y range
countdown = list(range(10,0,-1))
while countdown:
  current = countdown.pop(0)
  print(current)
  if not countdown:
    print("Despegue")

# prompt: genera un numero aleatoreo entre 1 a 100, captura ese valor generado en la variable valor_aleatoreo, luego pude por pantalla que el usuario ingrese un nnumero intentando adivinar el valor que se genero aleatoreamente, en caso de que no lo acierte, dale una ppista conm lazo if mencionado que "el numero a adivinar es mayor al digitado" o es "menor al difgitado", en caso de que si acierte muestra en pantalla el mensaje "Has adivinado en el intento Y, el valor generado fue XX",   el usuario tendra hasta 10 intentos.

import random

valor_aleatoreo = random.randint(1, 100)
intentos = 0

while intentos < 10:
  try:
    numero_usuario = int(input("Intenta adivinar el número (entre 1 y 100): "))
    intentos += 1

    if numero_usuario == valor_aleatoreo:
      print(f"Has adivinado en el intento {intentos}, el valor generado fue {valor_aleatoreo}")
      break
    elif numero_usuario < valor_aleatoreo:
      print("El número a adivinar es mayor al digitado.")
    else:
      print("El número a adivinar es menor al digitado.")

  except ValueError:
    print("Por favor, ingresa un número válido.")

if intentos == 10:
  print(f"No adivinaste el número. El número era {valor_aleatoreo}")

"""#**2 - Funciones en Python**

##**2.1 - Uso de Funciones con una variable en el resultado**
"""

def area_rectangulo(base, altura):
  area = base * altura
  return area

# Concepto de PROCEDIMIENTO
# Cuando invocamos o llamamos a un bloque de codigo creado con "def"
# y solo enviamos datos a pantalla
# no estamos retornando o devolviendo la informacion calculada
# por lo cual a este tipo de bloque de código o programa pequeño se lo conoce como procedimiento

# En este caso el bloque "def" se comporta como UN PROCEDIMIENTO
# porque no devuelve datos al programa que lo invoco (al programa mas grande)

def calculo_area_pantalla (base , altura):
  area = base * altura
  print(area)

lado1 = 5
lado2 = 10

calculo_area_pantalla( lado1 , lado2)

# Concepto de FUNCIÓN
#
# Cuando invocamos o llamamos a un bloque de codigo creado con "def"
# y SI enviamos datos resultantes al programa que nos llamo o invico
# estaremos usando "return" para retornar o devolvero la informacion calculada
# al programa más grande que nos llamo, en ese caso
# este tipo de bloque de código o programa pequeño se lo conoce como funcion

# En este caso el bloque "def" se comporta como UNA FUNCION
# porque SI  devuelve datos al programa que lo invoco (al programa mas grande)

def calculo_area_numerica (base , altura):
  area = base * altura
  return area

# Calculamos el área del rectangulo invocando una función creada con "def"
# lado1 = 5
# lado2 = 10

# Invoco a mi función que devuelve un valor numerico y lo capturo en una variable
# del programa mas grande que llamo a esa función

area_calculada = calculo_area_numerica(lado1, lado2)
#print(area_calculada)
print(f"El área del rectangulo de lado1= {lado1} y lado2= {lado2} es: {area_calculada}")

# Creamos la función que se encargie de calcular del Perimetro de un rectangulo
#
# En este caso el bloque "def" debe devolver el valor calculado

def perimeto_rectangulo_numerico (base , altura):
  perimetro = (base * 2) + (altura * 2)
  return perimetro

# Calculamos el perimetro del rectangulo invocando otra función creada con "def"
# lado1 = 5
# lado2 = 10

# Invoco a mi función que devuelve un valor numerico y lo capturo en una variable
# del programa más grande que llamo a esa función

perimetro_calculado = perimeto_rectangulo_numerico(lado1, lado2)
print(f"El perimetro del rectangulo de lado1= {lado1} y lado2= {lado2} es: {perimetro_calculado }")

# Creamos la función que se encargue de calcular el
# el área
# el perimetro y
# el perimetro al cuadrado
#
# En este caso el bloque "def" debe devolver tres datos calculados

def area_perimetro_perimetrocuadrado (base , altura):
  area = base * altura
  perimetro = (base * 2) + (altura * 2)
  perimetrocuadrado = perimetro ** 2

  return area, perimetro, perimetrocuadrado

# Calculamos el area, perimetro y perimtro al cuadrado y los capturamos en el programa más grande
# lado1 = 5
# lado2 = 10

# Invoco a mi función que puede calcular varos valores y devolver varios valores

area1, perimetro1, perimetrocuadrado1 = area_perimetro_perimetrocuadrado (lado1, lado2)

print(f"Para un rectangulo de lado1= {lado1} y lado2= {lado2}")
print(f"El area es: {area1}, el perimetro es {perimetro1} y el perimetro al cuadrado es {perimetrocuadrado1}")

# Calculamos el area, perimetro y perimtro al cuadrado y los capturamos en el programa más grande
# lado1 = 5
# lado2 = 10

# Invoco a mi función que puede calcular varos valores y devolver varios valores

area1, perimetro1, perimetrocuadrado1 = area_perimetro_perimetrocuadrado (lado1, lado2)

print(f"Para un rectangulo de lado1= {lado1} y lado2= {lado2}")
print(f"El area es: {area1}\nEl perimetro es {perimetro1}\nY el perimetro al cuadrado es {perimetrocuadrado1}")